name: hackweek
channels:
  - conda-forge
dependencies:
  - bokeh
  - cartopy
  - contextily
  - dask
  - dask-labextension
  - datashader
  - descartes
  - distributed
  - fiona
  - folium
  - fsspec
  - gdal
  - geoalchemy2
  - geojson
  - geopandas
  - geoviews
  - gh
  - git
  - h5py
  - holoviews
  - hvplot
  - icepyx
  - ipyleaflet
  - ipympl
  - ipywidgets
  - ipython-sql
  - jupyter-book=0.10.2
  - jupyterhub-singleuser
  - jupyter-server-proxy
  - jupyterlab-git
  - jupyterlab>=3.0.13
  - jupyter-resource-usage
  - matplotlib
  - nbgitpuller=0.9
  - numpy
  - pandas=1.2
  - panel
  - param>=1.11.1
  - pillow
  - pip
  - psycopg2
  - pycrs
  - pyproj
  - python=3.8
  - rasterio
  - rioxarray
  - requests
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - setuptools<58 
  - shapely
  - tensorflow=2.5
  - zarr
  - pip:
    - sphinxcontrib-bibtex==2.2.0
    - git+https://github.com/snowex/snowexsql.git
    - git+https://github.com/snowex-hackweek/snowmicropyn.git@master
    - git+https://github.com/ICESat2-SlideRule/sliderule-python@v1.0.7
    - git+https://github.com/ulmo-dev/ulmo.git@v0.8.7
